package com.jia54321.utils.jfinal.activerecord.generator.domain;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;
import com.jia54321.utils.entity.query.*;
import com.jia54321.utils.jfinal.activerecord.config.BaseModel;

import java.util.Map;

/**
 * Vo对象 
 * Generated by GG, do not modify this file.
 */
@ApiModel(value = "会员信息")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class TParkGroupOperateLogVO {
/**
 */

/**
  selectList 带别名的查询列表, 拼接查询条件
    <if test="id != null  and id != ''">and tabX.id = #{voX.id}</if>
    <if test="nodeId != null  and nodeId != ''">and tabX.node_id = #{voX.nodeId}</if>
    <if test="groupId != null  and groupId != ''">and tabX.group_id = #{voX.groupId}</if>
    <if test="seatId != null  and seatId != ''">and tabX.seat_id = #{voX.seatId}</if>
    <if test="agentId != null  and agentId != ''">and tabX.agent_id = #{voX.agentId}</if>
    <if test="parkCode != null  and parkCode != ''">and tabX.park_code = #{voX.parkCode}</if>
    <if test="regionCode != null  and regionCode != ''">and tabX.region_code = #{voX.regionCode}</if>
    <if test="carId != null  and carId != ''">and tabX.car_id = #{voX.carId}</if>
    <if test="carType != null  and carType != ''">and tabX.car_type = #{voX.carType}</if>
    <if test="remark != null  and remark != ''">and tabX.remark = #{voX.remark}</if>
    <if test="operateTime != null  and operateTime != ''">and tabX.operate_time = #{voX.operateTime}</if>
    <if test="operatorNo != null  and operatorNo != ''">and tabX.operator_no = #{voX.operatorNo}</if>
    <if test="operateType != null  and operateType != ''">and tabX.operate_type = #{voX.operateType}</if>
    <if test="operateDay != null  and operateDay != ''">and tabX.operate_day = #{voX.operateDay}</if>
 */

/**
  batchInsert
  tab字段
   <if test="item.id != null  and voX.id != ''">id,</if>
   <if test="item.nodeId != null  and voX.nodeId != ''">node_id,</if>
   <if test="item.groupId != null  and voX.groupId != ''">group_id,</if>
   <if test="item.seatId != null  and voX.seatId != ''">seat_id,</if>
   <if test="item.agentId != null  and voX.agentId != ''">agent_id,</if>
   <if test="item.parkCode != null  and voX.parkCode != ''">park_code,</if>
   <if test="item.regionCode != null  and voX.regionCode != ''">region_code,</if>
   <if test="item.carId != null  and voX.carId != ''">car_id,</if>
   <if test="item.carType != null  and voX.carType != ''">car_type,</if>
   <if test="item.remark != null  and voX.remark != ''">remark,</if>
   <if test="item.operateTime != null  and voX.operateTime != ''">operate_time,</if>
   <if test="item.operatorNo != null  and voX.operatorNo != ''">operator_no,</if>
   <if test="item.operateType != null  and voX.operateType != ''">operate_type,</if>
   <if test="item.operateDay != null  and voX.operateDay != ''">operate_day,</if>

  Vo字段
   <if test="item.id != null  and voX.id != ''">#{tabX.id},</if>
   <if test="item.nodeId != null  and voX.nodeId != ''">#{tabX.node_id},</if>
   <if test="item.groupId != null  and voX.groupId != ''">#{tabX.group_id},</if>
   <if test="item.seatId != null  and voX.seatId != ''">#{tabX.seat_id},</if>
   <if test="item.agentId != null  and voX.agentId != ''">#{tabX.agent_id},</if>
   <if test="item.parkCode != null  and voX.parkCode != ''">#{tabX.park_code},</if>
   <if test="item.regionCode != null  and voX.regionCode != ''">#{tabX.region_code},</if>
   <if test="item.carId != null  and voX.carId != ''">#{tabX.car_id},</if>
   <if test="item.carType != null  and voX.carType != ''">#{tabX.car_type},</if>
   <if test="item.remark != null  and voX.remark != ''">#{tabX.remark},</if>
   <if test="item.operateTime != null  and voX.operateTime != ''">#{tabX.operate_time},</if>
   <if test="item.operatorNo != null  and voX.operatorNo != ''">#{tabX.operator_no},</if>
   <if test="item.operateType != null  and voX.operateType != ''">#{tabX.operate_type},</if>
   <if test="item.operateDay != null  and voX.operateDay != ''">#{tabX.operate_day},</if>
 */

/**
  batchUpdate
    id = CASE id
	<foreach collection="list" item="item" index="index" open="" separator="" close="">
		WHEN #{item.id} THEN #{item.id}
	</foreach>
	END,
    node_id = CASE id
	<foreach collection="list" item="item" index="index" open="" separator="" close="">
		WHEN #{item.id} THEN #{item.nodeId}
	</foreach>
	END,
    group_id = CASE id
	<foreach collection="list" item="item" index="index" open="" separator="" close="">
		WHEN #{item.id} THEN #{item.groupId}
	</foreach>
	END,
    seat_id = CASE id
	<foreach collection="list" item="item" index="index" open="" separator="" close="">
		WHEN #{item.id} THEN #{item.seatId}
	</foreach>
	END,
    agent_id = CASE id
	<foreach collection="list" item="item" index="index" open="" separator="" close="">
		WHEN #{item.id} THEN #{item.agentId}
	</foreach>
	END,
    park_code = CASE id
	<foreach collection="list" item="item" index="index" open="" separator="" close="">
		WHEN #{item.id} THEN #{item.parkCode}
	</foreach>
	END,
    region_code = CASE id
	<foreach collection="list" item="item" index="index" open="" separator="" close="">
		WHEN #{item.id} THEN #{item.regionCode}
	</foreach>
	END,
    car_id = CASE id
	<foreach collection="list" item="item" index="index" open="" separator="" close="">
		WHEN #{item.id} THEN #{item.carId}
	</foreach>
	END,
    car_type = CASE id
	<foreach collection="list" item="item" index="index" open="" separator="" close="">
		WHEN #{item.id} THEN #{item.carType}
	</foreach>
	END,
    remark = CASE id
	<foreach collection="list" item="item" index="index" open="" separator="" close="">
		WHEN #{item.id} THEN #{item.remark}
	</foreach>
	END,
    operate_time = CASE id
	<foreach collection="list" item="item" index="index" open="" separator="" close="">
		WHEN #{item.id} THEN #{item.operateTime}
	</foreach>
	END,
    operator_no = CASE id
	<foreach collection="list" item="item" index="index" open="" separator="" close="">
		WHEN #{item.id} THEN #{item.operatorNo}
	</foreach>
	END,
    operate_type = CASE id
	<foreach collection="list" item="item" index="index" open="" separator="" close="">
		WHEN #{item.id} THEN #{item.operateType}
	</foreach>
	END,
    operate_day = CASE id
	<foreach collection="list" item="item" index="index" open="" separator="" close="">
		WHEN #{item.id} THEN #{item.operateDay}
	</foreach>
	END,
 */

/**
  cloumn
	<result column="id" property="id" jdbcType="BIGINT" />
	<result column="node_id" property="nodeId" jdbcType="INTEGER" />
	<result column="group_id" property="groupId" jdbcType="BIGINT" />
	<result column="seat_id" property="seatId" jdbcType="BIGINT" />
	<result column="agent_id" property="agentId" jdbcType="BIGINT" />
	<result column="park_code" property="parkCode" jdbcType="VARCHAR" />
	<result column="region_code" property="regionCode" jdbcType="VARCHAR" />
	<result column="car_id" property="carId" jdbcType="VARCHAR" />
	<result column="car_type" property="carType" jdbcType="INTEGER" />
	<result column="remark" property="remark" jdbcType="VARCHAR" />
	<result column="operate_time" property="operateTime" jdbcType="BIGINT" />
	<result column="operator_no" property="operatorNo" jdbcType="VARCHAR" />
	<result column="operate_type" property="operateType" jdbcType="INTEGER" />
	<result column="operate_day" property="operateDay" jdbcType="INTEGER" />
 */

/**
  Vo字段
   #{voX.id}, #{voX.nodeId}, #{voX.groupId}, #{voX.seatId}, #{voX.agentId}, #{voX.parkCode}, #{voX.regionCode}, #{voX.carId}, #{voX.carType}, #{voX.remark}, #{voX.operateTime}, #{voX.operatorNo}, #{voX.operateType}, #{voX.operateDay},
  tab字段
   tabX.id, tabX.node_id, tabX.group_id, tabX.seat_id, tabX.agent_id, tabX.park_code, tabX.region_code, tabX.car_id, tabX.car_type, tabX.remark, tabX.operate_time, tabX.operator_no, tabX.operate_type, tabX.operate_day,









 */

	@ApiModelProperty(value="", dataType = "java.lang.Long")
	private java.lang.Long id;

	@ApiModelProperty(value="", dataType = "java.lang.Integer")
	private java.lang.Integer nodeId;

	/**  组id  */
	@ApiModelProperty(value="组id", dataType = "java.lang.Long")
	private java.lang.Long groupId;

	/**  车位号  */
	@ApiModelProperty(value="车位号", dataType = "java.lang.Long")
	private java.lang.Long seatId;

	@ApiModelProperty(value="", dataType = "java.lang.Long")
	private java.lang.Long agentId;

	/**  停车场编号  */
	@ApiModelProperty(value="停车场编号", dataType = "java.lang.String")
	private java.lang.String parkCode;

	/**  区域编号  */
	@ApiModelProperty(value="区域编号", dataType = "java.lang.String")
	private java.lang.String regionCode;

	/**  车牌号  */
	@ApiModelProperty(value="车牌号", dataType = "java.lang.String")
	private java.lang.String carId;

	/**  车辆类型  */
	@ApiModelProperty(value="车辆类型", dataType = "java.lang.Integer")
	private java.lang.Integer carType;

	@ApiModelProperty(value="", dataType = "java.lang.String")
	private java.lang.String remark;

	/**  操作时间  */
	@ApiModelProperty(value="操作时间", dataType = "java.lang.Long")
	private java.lang.Long operateTime;

	/**  操作员编号  */
	@ApiModelProperty(value="操作员编号", dataType = "java.lang.String")
	private java.lang.String operatorNo;

	/**  操作类型：1创建，2修改，3新增车位，4删除，5启用，6暂停，7延期，8新增车辆，9删除车辆  */
	@ApiModelProperty(value="操作类型：1创建，2修改，3新增车位，4删除，5启用，6暂停，7延期，8新增车辆，9删除车辆", dataType = "java.lang.Integer")
	private java.lang.Integer operateType;

	/**  操作增加天数  */
	@ApiModelProperty(value="操作增加天数", dataType = "java.lang.Integer")
	private java.lang.Integer operateDay;

}

